# ------------------------------------------------------------------------------
# More resources related to this file:
# [1] Overview   | https://docs.docker.com/compose/
# [2] PostgreSQL | https://github.com/docker-library/docs/tree/master/postgres
# [3] Node.js    | https://github.com/nodejs/docker-node/blob/master/README.md#how-to-use-this-image
# -------------
#  More resources for your projects:
# [4] Samples    | https://github.com/docker/awesome-compose
# [5] Env Vars   | https://docs.docker.com/compose/environment-variables/
# [6] Secrets    | https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose
# ------------------------------------------------------------------------------

services:
  heroku-cli:
    build: ./heroku
    env_file: ./heroku/.env

  db:
    build: ./init_data
    env_file: .env
    expose:
      - "5432"                                  # We need only expose port `5432` internally to node (not the host)
    volumes:
      - buff_forums_volume:/var/lib/postgresql/data  # Creates a docker managed volume to persist your data.
      - ./init_data:/docker-entrypoint-initdb.d  #Binds init_data to docker-entrypoint-initdb.d

  web:
    build: 
      context: ./
      dockerfile: Dockerfile
      target: devapp
    depends_on:
      - db                                      
    env_file: .env
    ports:
        - "3000:3000" 
    volumes:
      - ./:/home/node/app/src

    # command: "npm run testandrun"

volumes:
  buff_forums_volume: {}
  
  
